# Generated by Django 4.2.7 on 2024-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='story_point',
            field=models.IntegerField(default=0),
        ),
    ]
