# name: build-and-deploy

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
#       - staging

# env:
#   TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

# jobs:
#   # To build the project
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checking out code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.12

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r req.txt

#   deploy_staging:
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.event.pull_request.base.ref == 'staging'

#     steps:
#       - name: Deploy to Staging
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           script: |
#             cd plane-project-staging/plane_api
#             python manage.py migrate

deploy:
  name: Deploying on EC2 via SSH
  if: ${{ github.event_name == 'push' }}
  runs-on: ubuntu-latest
  steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sh ec2-deploy.sh
