name: Your Workflow Name
on:
  push:
    branches:
      - testing
deploy:
  name: Deploying on EC2 via SSH
  if: ${{ github.event_name == 'push' }}
  runs-on: ubuntu-latest
  steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sh ec2-deploy.sh
